sudo: false
dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - "pip install --upgrade pip"
  - "pip install pipenv"
  - "pipenv install"
script:
  - "pipenv run time python -m unittest"
branches:
  only:
    - master